### ISSUE TITLE
raise exc.NoSuchModuleError( sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:mongodb.srv

### ISSUE THREAD

**Issue by Bmgpt** [michael2to3/fakegeobot#7]
Hi Micheal,

I try to run the fakegeobot on replit, but I got this error. Can you please help to guide me. What should I do?

<img width="467" alt="image" src="https://github.com/michael2to3/fakegeobot/assets/137195478/e8c3c158-02dd-4f1c-b473-bf9f7bde80d5">

**Comment by michael2to3** [comment]
Hi, can u show me .env file without cred like API_ID, HASH, TOKEN

**Comment by Bmgpt** [comment]
Hi michael, share with me your telegram so that I can contact you personally.

**Comment by michael2to3** [comment]
t.me/michael2to3
